### ISSUE TITLE
eXtploer FTP mode fails to display VRootAlias FTP diretories

### ISSUE THREAD

**Issue by dfc-d** [OpenMediaVault-Plugin-Developers/openmediavault-extplorer#2]
In FTP mode eXtplorer fails to display the 'shares' as directories in the ProFTPd virtual chroot. Using FileZilla (on Windows) the VRootAlias dirs (the 'Shares' from the OMV FTP Web UI) are visible as directories in '/' (root).

Steps to reproduce:

1) Enable FTP
2) Create 'Shared Directories' and give permissions to some user
3) Add 'Shared Directories' as Shares in FTP Web UI
4) Use eXtplorer FTP mode as that user
5) Observe that one sees only an empty '/' (root)

**Comment by dfc-d** [comment]
Purpose was to have proper per-use authentication on the NAS - i.e. as HTTP-based file explorer it is only available to the admin user (at least in a sensibly secure installation).  FTP-based eXtplorer would apply proper ACLs to the files non-privileged users could see and access.

**Comment by dfc-d** [comment]
I mean while giving the user a web browser interface too - i.e. not via an ftp client, but via a http server running on the NAS,.

**Comment by ryecoaaron** [comment]
Over a year later... I think this is an extplorer issue.

**Comment by dfc-d** [comment]
I moved on to other thing and happened to notice the open issue in my 
github issues.  So sue me.

Regards,

Daniel

**Comment by dfc-d** [comment]
Also note, I don't actually care if you fix the bug - I've moved onto 
other things and don't use OMV any more.

I was merely providing use case information and the reason the bug was 
of interest when I raised it so that if it was a scenario you cared 
about you could figure out what you wanted to do about it.

IoW the bug and this late followup is as service to you, and not as an 
issue I care if you fix for me use.

So if that means you don't care about this scenario I don't really care 
- it doesn't affect me in way, shape, or form.  If this is a scenario 
you think would be useful to support (non-privileged users having a web 
browser interface to files to which they have access on the NAS, without 
giving them an interface that give them root rights to the filesystem 
like eXplorer would if you added additional users to the non-FTP 
interface) then you can think about how you want to support it.

If you don't care about the scenario then that's really up to you, I was 
merely providing the reason so you could do what you wanted with the 
information.

**Comment by ryecoaaron** [comment]
Geez dude, chill out.  All I said is that this is an extplorer issue.  I can't fix it.  If that means you can't use it, sorry.  There are probably other ftp web clients out there.  extplorer has other issues as well.  I do what I can with the little time I volunteer to this project...

**Comment by dfc-d** [comment]
Sorry, was just taking it by the year later comment, in combination with 
the other that you were getting crusty about the bug report.  Reading 
too much into the written words I guess.

Also I also tend to be verbose even when I'm not excited or upset, so if 
you think I'm terribly upset; I'm not, I just talk a lot and say what I 
think, in detail.

I think that also tends to get too much read into it, and assumed to be 
a sign of more emotion than is actually the case.

Perhaps I try to hard to be understood, but that's just how I am.

Regards,

Daniel

**Comment by dfc-d** [comment]
Oh, also this issue is not *why* I don't use OMV; it would just have 
been 'nice to have'.

My reasons for not using OMV have more to do with what I looking for a 
convenient web interface where possible, a normal debian (although the 
particular distro wasn't important to me, it just happends to the basis 
of OMV) distribution otherwise, but I found that the things OMV does to 
allow the web interface interfered too much with the kinds of things I 
wanted to do that weren't/aren't part OMV (and wasn't inclined to hack 
on OMV to get due to having other more immediate and pressing concerns).

I've ended up without the convenient web ui, but again, nice web ui is 
just 'nice to have', not something I desperately need (allowing regular 
users to browse files via web browser would have been pretty sweet, but 
isn't going to change to world or my life).

Regards,

Daniel

**Comment by dfc-d** [comment]
Put it this way, I'm a fairly fast touch typist who tends to 
over-explain and sometimes gets verbal diaherria and hadn't realized 
that people tend to assume that lots of words in email and similar means 
a great deal of excitement and hence read in more than is actually there 
(a common problem with written (esp. internet) communication in general, 
really).

Regards,

Daniel
