### ISSUE TITLE
Automatic update of eXtplorer

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-extplorer#3]
Is it possible to allow us to upgrade the installed eXtplorer version?

I see than 2.1.8 has been released for months and we can't update ours in the plugin.

Thanks.

**Comment by ryecoaaron** [comment]
extplorer isn't updated often enough to need automatic update or justify writing the code to do it.  The last changes were considered minor.  If someone just notifies me when there is an update, it doesn't take much to update the plugin and release the update.  That said, the update is in the repo.

**Comment by anderbytes** [comment]
Thanks a lot.

To me, having a update againt CSRF attacks in 2.1.8 is reason enough to update  ;-)
